version: '3.8'
services:
  app:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /home/dinodev/nginxproxymanager:/data
      - /home/dinodev/nginxproxymanager:/etc/letsencrypt
