services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - '7000:3000'
    volumes:
      - '/home/dinodev/grafana/data:/var/lib/grafana' # permanent storage
